AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  MyCookBookApi

  Sample SAM Template for MyCookBookApi

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    Environment:
      Variables:
        KmsResourceKey: "alias/managedSecretKeys"
        EncryptedSecrets: "AQICAHhU+xgK1oJI4Kvxli5TFSmDFgJcylDHyErXuXKVirBevgFrEhnJLAqEgFLfEcUvlrYuAAABDzCCAQsGCSqGSIb3DQEHBqCB/TCB+gIBADCB9AYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwT1ke5ntdeEmsTo/ICARCAgcYKXtpTDTgYgjYIf37lFuaXaG87VLQzrA14etMkcsThZFdF/VthOpbpB4OT7UUdbh6RUa49Wo1d8Jay0em2wU6QlkYHRsj/ea/eINo3gr98WVaq1RHHjcInrNL6uG+sX/a0Af3DeK9Gg01ZWAqXjsEVOhSYLMd3yTgceiUUZdzK7FwQhsvLxd1aOMP+ZGahXRQh0X5ASAcVdyAH+Nm6CbWq31X0j875V9clzYbcnjmdLADzxjMRqu+rQiDwmgu9+nrgReX3L+k="

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: API
      StageName: Test
      Cors:
        AllowMethods: "'DELETE,GET,HEAD,OPTIONS,PATCH,POST,PUT'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"
  APIRoutes:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: nodejs18.x
      CodeUri: .
      Handler: src/app.lambdaHandler
      Events:
        APIEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /{proxy+}
            Method: ANY
    Metadata: # Manage esbuild properties
      BuildMethod: esbuild
      BuildProperties:
        Minify: true
        Target: es2020
        Sourcemap: true
        EntryPoints:
        - src/app.ts
